const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {convertReports}=require('./temporal/converter.js');
const files=process.argv.slice(2);
assert.equal(files.length,3,'Pass three local report paths');
const inputs=files.map(file=>({name:path.basename(file),html:fs.readFileSync(file,'utf8')}));
const result=convertReports(inputs);
assert.equal((result.html.match(/<table>/g)||[]).length,6);
assert.equal((result.html.match(/<h3>Settle latency<\/h3>/g)||[]).length,3);
assert.ok(result.results.every(r=>r.files>0));
assert.throws(()=>convertReports(inputs.slice(0,2)),/three/);
const mutate=html=>[{...inputs[0],html},...inputs.slice(1)];
assert.throws(()=>convertReports(mutate('<html>Not a report</html>')),/No recording/);
assert.throws(()=>convertReports(mutate(inputs[0].html.replace(/\bA (\d+) \(/g,(_,n)=>'A '+(+n+1)+' ('))),/mismatch/);
assert.throws(()=>convertReports(mutate(inputs[0].html.replace('class="metric-main"','class="metric-main"').replace(/median [\d.]+/g, 'median missing'))));
const unsafe=convertReports(inputs.map(x=>({...x,name:'<img src=x onerror=alert(1)>.html'}))).html;
assert.ok(!unsafe.includes('<img'));
assert.ok(unsafe.includes('&lt;img'));
assert.ok(!result.html.includes('file:///'));
console.log('Passed: real reports, six tables, invalid reports, changed counts, missing latency, and escaped filenames.');
console.log(JSON.stringify(result.results.map(r=>({files:r.files,latency:r.settleLatency.all})),null,2));
