const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {convertReports}=require('./temporal/converter.js');
const files=process.argv.slice(2);
assert.ok(files.length>=2,'Pass at least two local report paths');
const inputs=files.map((file,i)=>({name:path.basename(file),title:'Config '+(i+1),html:fs.readFileSync(file,'utf8')}));
const result=convertReports(inputs,{title:'Regression run'});
const stages=[...new Set(result.results.flatMap(r=>r.stages))];
assert.ok(result.html.includes('<h1>Regression run</h1>'),'report title is used');
assert.ok(result.html.includes('<h2>1. Config 1</h2>'),'configuration titles are used');
assert.equal((result.html.match(/<table>/g)||[]).length,1+2*inputs.length);
assert.equal((result.html.match(/<h3>Settle latency<\/h3>/g)||[]).length,inputs.length);
assert.ok(result.results.every(r=>r.files>0));
assert.ok(result.results.every(r=>r.scopeOrder.includes('Thumb')),'thumb is its own scope');
for(const stage of stages) assert.ok(['S','T','EF'].includes(stage));
if(stages.includes('EF')) assert.ok(result.html.includes('EdgeFilter − Temporal'),'EdgeFilter delta row');
assert.throws(()=>convertReports(inputs.slice(0,1)),/at least two/);
const mutate=html=>[{...inputs[0],html},...inputs.slice(1)];
assert.throws(()=>convertReports(mutate('<html>Not a report</html>')),/No recording/);
assert.throws(()=>convertReports(mutate(inputs[0].html.replace(/\bA (\d+) \(/g,(_,n)=>'A '+(+n+1)+' ('))),/mismatch/);
assert.throws(()=>convertReports(mutate(inputs[0].html.replace(/median [\d.]+/g,'median missing'))),/latency/);
const unsafe=convertReports(inputs.map(x=>({...x,name:'<img src=x onerror=alert(1)>.html',title:'<img src=x>'}))).html;
assert.ok(!unsafe.includes('<img'));
assert.ok(unsafe.includes('&lt;img'));
assert.ok(!result.html.includes('file:///'));
console.log(`Passed with ${inputs.length} reports, stages ${stages.join('/')}: titles, tables, invalid reports, changed counts, missing latency, and escaped names.`);
console.log(JSON.stringify(result.results.map(r=>({title:r.title,files:r.files,stages:r.stages,scopes:r.scopeOrder,reconciled:r.reconciled,latency:r.settleLatency.all})),null,2));
